/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Component1: typeof import('./src/components/Component1.vue')['default']
    Component1Skeleton: typeof import('./src/components/Component1Skeleton.vue')['default']
    Component2: typeof import('./src/components/Component2.vue')['default']
    Component2Skeleton: typeof import('./src/components/Component2Skeleton.vue')['default']
    Component3: typeof import('./src/components/Component3.vue')['default']
    Component3Skeleton: typeof import('./src/components/Component3Skeleton.vue')['default']
    Component4: typeof import('./src/components/Component4.vue')['default']
    Component4Skeleton: typeof import('./src/components/Component4Skeleton.vue')['default']
    Component5: typeof import('./src/components/Component5.vue')['default']
    Component5Skeleton: typeof import('./src/components/Component5Skeleton.vue')['default']
    DefaultErrorComponent: typeof import('./src/components/DefaultErrorComponent.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    LazyComponent1: typeof import('./src/components/LazyComponent1.vue')['default']
    LazyComponent1Skeleton: typeof import('./src/components/LazyComponent1Skeleton.vue')['default']
  }
}
