/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
import { DefineComponent } from 'vue';
        
type DeepPartial<T> = Partial<{
    [P in keyof T]: DeepPartial<T[P]> | {
        [key: string]: string | object;
    };
}>;

type LazyComponentOptions = {
  delay?: number;
  errorComponentPath?: string;
  loadData?: () => Promise<unknown>;
  timeout?: number;
  priority?: 'visible-first' | 'immediate';
  intersectionObserver: IntersectionObserverInit;
}

declare module 'vue' {
  export interface GlobalComponents {
    LazyComponent1: typeof import('./src/components/Component1.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyComponent2: typeof import('./src/components/Component2.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyComponent3: typeof import('./src/components/Component3.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyComponent4: typeof import('./src/components/Component4.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyComponent5: typeof import('./src/components/Component5.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyError: typeof import('./src/components/Error.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
    LazyComponent1: typeof import('./src/components/LazyComponent1.vue')['default'] extends DefineComponent<infer PropsOrPropOptions, infer RawBindings, infer D, infer C, infer M, infer Mixin, infer Extends, infer E, infer EE, infer PP, infer Props, infer Emits>
              ? DefineComponent<PropsOrPropOptions & DeepPartial<LazyComponentOptions>, RawBindings, D, C, M, Mixin, Extends, E, EE, PP, Props & DeepPartial<LazyComponentOptions>, Emits> 
              : never
  }
}
